### ISSUE TITLE
Suggestion: add .xcodeproj to gitignore

### ISSUE THREAD

**Issue by cweinberger** [ryangrimm/VaporElasticsearch#10]
As the xcode project will be generated by vapor automatically, we shouldn't commit it to the repository.

Example `.gitignore`: https://github.com/nodes-vapor/template/blob/master/.gitignore

What do you think?

@ryangrimm

**Comment by ryangrimm** [comment]
Absolutely can and should. I initially checked it in for my own convenience but you're right, it really doesn't need to be there. Removed now.
