### ISSUE TITLE
Support script_score and function_score

### ISSUE THREAD

**Issue by obrhoff** [ryangrimm/VaporElasticsearch#17]
Hey,

So far great work! Would it maybe be possible to get support for function score and script score? 

https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-function-score-query.html

https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-function-score-query.html#function-script-score

**Comment by jonnymacs** [comment]
@docterd these features were added on a fork https://github.com/Leafly-com/VaporElasticsearch/tree/function_score_query

I've been building on top of this branch. Hoping to get @ryangrimm to merge this all back in when he has time :)
